# config.py
import math


WIDTH, HEIGHT = 1280, 720
FPS = 60


GROUND_Y = HEIGHT * 2 // 3
CHUNK = 20
PLAYER_DOWNHILL_SPEED = 12
DOWNHILL_SLOPE_FACTOR = 4.0
PLAYER_SCREEN_X = WIDTH // 4
PLAYER_TARGET_SCREEN_Y = HEIGHT * 2 // 3
TREE_LINE_WORLD_Y_OFFSET = 50


PLAYER_ANIMATION_SPEED = 0.1 
PLAYER_TARGET_WIDTH = 55     
PLAYER_TARGET_HEIGHT = 85    
                             


AVALANCHE_SPEED = 0.25
AVALANCHE_SHAKE_MAGNITUDE = 10  
AVALANCHE_SHAKE_DURATION = 0.75 
GRAVITY = 0.6
JUMP_VEL = -16
MAX_JUMPS = 2
CHECKPOINT_DISTANCES = [i * 150 for i in range(1, 11)] 


MAX_PLAYER_HEALTH = 100
OBSTACLE_SPAWN_INTERVAL_MIN = 1600
OBSTACLE_SPAWN_INTERVAL_MAX = 3000
MAX_OBSTACLES_ON_SCREEN = 5
OBSTACLE_SPRITE_WIDTH = 100  
OBSTACLE_SPRITE_HEIGHT = 190 


ICE_SPIKE_OVERLAY_WIDTH = 60
ICE_SPIKE_OVERLAY_HEIGHT = 180
ICE_SPIKE_IMAGE_FILENAME = "SpikeImage.png"


BUG_OBSTACLE_ENABLED = True
BUG_SPRITE_WIDTH = 130 
BUG_SPRITE_HEIGHT = 95 
BUG_ANIMATION_SPEED = 0.2
BUG_MOVE_SPEED = 2.5
BUG_DAMAGE_VALUE = 15
BUG_DEBRIS_MATERIAL = "bug_flesh"
BUG_SPAWN_INTERVAL_MIN_L2 = 2500
BUG_SPAWN_INTERVAL_MAX_L2 = 4500
MAX_BUGS_ON_SCREEN_L2 = 3



BOULDER_ENABLED_L2 = True
BOULDER_TARGET_WIDTH = 300
BOULDER_TARGET_HEIGHT = 300
BOULDER_ROTATION_SPEED_DEG_PER_PIXEL = 10


BOULDER_SPEED_PER_FRAME = 0.25
BOULDER_CATCHUP_SPEED_BONUS_PER_FRAME = 0.50
BOULDER_INITIAL_OFFSET = -WIDTH * 0.5

BOULDER_APPEAR_OFFSET = 0 


BOULDER_COLLISION_HORIZONTAL_INSET = 50
BOULDER_COLLISION_VERTICAL_INSET = 30

BOULDER_DEATH_SCREEN_DELAY_MS = 2800


BOULDER_WIN_PROXIMITY_THRESHOLD = 60 




CRYSTAL_OBSTACLE_ENABLED_L2 = True
CRYSTAL_SPRITE_FILENAME = "crystal.png"
CRYSTAL_SPRITE_WIDTH = 120
CRYSTAL_SPRITE_HEIGHT = 150
CRYSTAL_DAMAGE_VALUE = 35
CRYSTAL_DEBRIS_MATERIAL = "ice"
CRYSTAL_FALL_ACCELERATION = 0.3
CRYSTAL_INITIAL_FALL_VELOCITY = 0.0
CRYSTAL_SPAWN_Y_OFFSET_ABOVE_CEILING = 0
CRYSTAL_DESTRUCTION_SOUND_KEY = "spike_breaking_sound"
CRYSTAL_GROUND_IMPACT_SOUND_KEY = "crystal_ground_impact_sound_effect"
CRYSTAL_IMPACT_SHAKE_MAGNITUDE = 30
CRYSTAL_IMPACT_SHAKE_DURATION = 0.45
CRYSTAL_SPAWN_INTERVAL_MIN_L2 = 3500
CRYSTAL_SPAWN_INTERVAL_MAX_L2 = 6500




SLOWDOWN_DURATION = 2000
SLOWDOWN_FACTOR = 0.5


MAX_BULLETS = 20
LASER_SPEED_X = 20
LASER_GRAVITY = 0.2


FINAL_RAMP_HEIGHT_RISE = 700


SNOW_LAYERS = [
    {
        "count": 350, "speed_y_min": 0.4, "speed_y_max": 1.2, "base_speed_x_min": -0.1,
        "base_speed_x_max": 0.1, "parallax_x_factor": 0.1, "size_min": 1, "size_max": 1,
        "alpha_min": 40, "alpha_max": 90
    },
    {
        "count": 300, "speed_y_min": 1.2, "speed_y_max": 2.8, "base_speed_x_min": -0.2,
        "base_speed_x_max": 0.2, "parallax_x_factor": 0.35, "size_min": 1,
        "size_max": 2, "alpha_min": 80, "alpha_max": 160
    },
    {
        "count": 250, "speed_y_min": 2.8, "speed_y_max": 4.5, "base_speed_x_min": -0.3,
        "base_speed_x_max": 0.3, "parallax_x_factor": 0.75, "size_min": 2,
        "size_max": 3, "alpha_min": 130, "alpha_max": 210
    }
]


WIND_GUST_INTERVAL_MIN = 7000
WIND_GUST_INTERVAL_MAX = 12000
WIND_GUST_DURATION_MIN = 1500
WIND_GUST_DURATION_MAX = 3000
WIND_GUST_STRENGTH_X_MIN = -6.0
WIND_GUST_STRENGTH_X_MAX = -3.0
WIND_GUST_STRENGTH_Y_FACTOR = 0.1


PROCEDURAL_FOG_LAYERS_CONFIG = [
    {
        "color": (195, 205, 215),
        "y_offset_from_bottom": 5,
        "height_on_screen": 190,
        "num_main_puffs": 75,
        "puff_sub_puffs": 7,
        "puff_base_radius_min": 45,
        "puff_base_radius_max": 115,
        "puff_sub_radius_factor": 0.55,
        "puff_alpha_min": 20,
        "puff_alpha_max": 55,
        "scroll_factor": 0.06
    },
    {
        "color": (205, 215, 225),
        "y_offset_from_bottom": -25,
        "height_on_screen": 230,
        "num_main_puffs": 65,
        "puff_sub_puffs": 8,
        "puff_base_radius_min": 55,
        "puff_base_radius_max": 150,
        "puff_sub_radius_factor": 0.65,
        "puff_alpha_min": 15,
        "puff_alpha_max": 45,
        "scroll_factor": 0.09
    }
]
ENABLE_FOG_EFFECT = True


LEVEL2_TERRAIN_COLOR_OVERRIDE = (25, 30, 55)
LEVEL2_TERRAIN_GRADIENT_LIGHT_BLUE = (65, 85, 135)
LEVEL2_TERRAIN_GRADIENT_STRIPS = 10
LEVEL2_TERRAIN_HIGHLIGHT_COLOR = (45, 50, 75)

LEVEL2_CEILING_LIGHT_SPACING = 50
LEVEL2_CEILING_LIGHT_Y_OFFSET = 0
LEVEL2_CEILING_LIGHT_NUM_PARTICLES = 0
LEVEL2_CEILING_LIGHT_PARTICLE_RADIUS_MIN = 1
LEVEL2_CEILING_LIGHT_PARTICLE_RADIUS_MAX = 2
LEVEL2_CEILING_LIGHT_PARTICLE_SPREAD = 4
LEVEL2_CEILING_LIGHT_PARTICLE_COLORS = [
    (255, 255, 240), (250, 250, 220), (255, 250, 230)
]


L2_ROPE_LIGHTS_ENABLED = False
L2_ROPE_LIGHT_BASE_COLOR = (255, 230, 160)
L2_ROPE_LIGHT_RADIUS = 3
L2_ROPE_LIGHT_SPACING = 400
L2_ROPE_LIGHT_Y_OFFSET = -5
L2_ROPE_LIGHT_PULSE_SPEED_HZ = 0.8
L2_ROPE_LIGHT_PULSE_MIN_BRIGHTNESS_FACTOR = 0.6
L2_ROPE_LIGHT_GLOW_ENABLED = True
L2_ROPE_LIGHT_GLOW_RADIUS_FACTOR = 2.5
L2_ROPE_LIGHT_GLOW_BASE_ALPHA = 60
L2_ROPE_LIGHT_PULSE_PHASE_OFFSET_MAX_RAD = math.pi
L2_ROPE_LIGHT_FLICKER_SPEED_HZ = 2.5
L2_ROPE_LIGHT_FLICKER_MAGNITUDE = 0.15
L2_ROPE_LIGHT_FLICKER_PHASE_OFFSET_MAX_RAD = math.pi * 2
L2_ROPE_LIGHT_SWAY_ENABLED = True
L2_ROPE_LIGHT_SWAY_AMPLITUDE_X = 3.0
L2_ROPE_LIGHT_SWAY_SPEED_HZ = 0.3
L2_ROPE_LIGHT_SWAY_PHASE_OFFSET_MAX_RAD = math.pi * 2
L2_ROPE_LIGHT_HANGING_LINE_COLOR = (70, 70, 80, 120)


L2_PARTICLE_LIGHT_PULSE_SPEED_HZ = 0.6
L2_PARTICLE_LIGHT_PULSE_PHASE_OFFSET_MAX_RAD = math.pi
L2_PARTICLE_LIGHT_FLICKER_SPEED_HZ = 3.0
L2_PARTICLE_LIGHT_FLICKER_MAGNITUDE = 0.2
L2_PARTICLE_LIGHT_FLICKER_PHASE_OFFSET_MAX_RAD = math.pi * 2


L2_HANGING_LIGHTS_ENABLED = True
L2_HANGING_LIGHT_IMAGE_FILENAME = "hanging_light.png"
L2_HANGING_LIGHT_TARGET_WIDTH = 50
L2_HANGING_LIGHT_TARGET_HEIGHT = 60
L2_HANGING_LIGHT_SPACING = 300
L2_HANGING_LIGHT_SPAWN_X_VARIATION = 100
L2_HANGING_LIGHT_SPAWN_PROBABILITY = 0.9
L2_HANGING_LIGHT_Y_OFFSET_FROM_CEILING = -1
L2_MAX_HANGING_LIGHTS_ON_SCREEN = 10
L2_HANGING_LIGHT_MAX_SWING_ANGLE = 15.0
L2_HANGING_LIGHT_SWING_FREQUENCY = 1.5


L2_BLACK_PLATFORM_THICKNESS = 70
LAVA_START_OFFSET_BELOW_PLATFORM = 0
LAVA_LAYER_THICKNESS = 250

LAVA_GRADIENT_COLOR_TOP = (255, 100, 0)
LAVA_GRADIENT_COLOR_BOTTOM = (150, 20, 0)
LAVA_NUM_GRADIENT_LAYERS = 7

LAVA_PULSE_SPEED_HZ = 0.7
LAVA_PULSE_MAGNITUDE_RGB = (40, 25, 15)

LAVA_WAVE_AMPLITUDE = 5
LAVA_WAVE_FREQUENCY_SPATIAL = 0.025
LAVA_WAVE_FREQUENCY_TEMPORAL = 0.0025

LAVA_SURFACE_PARTICLES_ENABLED = True
LAVA_MAX_SURFACE_PARTICLES = 60
LAVA_PARTICLES_PER_FRAME_SPAWN = 2
LAVA_SURFACE_PARTICLE_COLOR_START = (255, 200, 50)
LAVA_SURFACE_PARTICLE_COLOR_END = (255, 100, 0)
LAVA_SURFACE_PARTICLE_SIZE_RANGE = (1, 3)
LAVA_SURFACE_PARTICLE_LIFE_MS = (400, 900)
LAVA_SURFACE_PARTICLE_RISE_SPEED_MIN = -1.0
LAVA_SURFACE_PARTICLE_RISE_SPEED_MAX = -0.4
LAVA_SURFACE_PARTICLE_FADE_POWER = 0.7


L2_GROUND_SMOKE_ENABLED = True
L2_GROUND_SMOKE_MAX_PARTICLES = 40
L2_GROUND_SMOKE_SPAWN_INTERVAL_MS = 150
L2_GROUND_SMOKE_PARTICLES_PER_SPAWN = 1
L2_GROUND_SMOKE_COLOR_START = (80, 70, 60, 100)
L2_GROUND_SMOKE_COLOR_END = (60, 50, 40, 0)
L2_GROUND_SMOKE_SIZE_RANGE = (8, 20)
L2_GROUND_SMOKE_LIFE_MS = (2000, 4500)
L2_GROUND_SMOKE_RISE_SPEED_MIN = -0.3
L2_GROUND_SMOKE_RISE_SPEED_MAX = -0.1
L2_GROUND_SMOKE_DRIFT_SPEED_MIN = -0.2
L2_GROUND_SMOKE_DRIFT_SPEED_MAX = 0.2
L2_GROUND_SMOKE_FADE_POWER = 1.0


L2_LAVA_SMOKE_ENABLED = True
L2_LAVA_SMOKE_MAX_PARTICLES = 60
L2_LAVA_SMOKE_SPAWN_INTERVAL_MS = 120
L2_LAVA_SMOKE_PARTICLES_PER_SPAWN = 2
L2_LAVA_SMOKE_COLOR_START = (60, 50, 40, 80)
L2_LAVA_SMOKE_COLOR_END = (40, 30, 20, 0)
L2_LAVA_SMOKE_SIZE_RANGE = (20, 45)
L2_LAVA_SMOKE_LIFE_MS = (3000, 6000)
L2_LAVA_SMOKE_RISE_SPEED_MIN = -0.6
L2_LAVA_SMOKE_RISE_SPEED_MAX = -0.25
L2_LAVA_SMOKE_DRIFT_SPEED_MIN = -0.1
L2_LAVA_SMOKE_DRIFT_SPEED_MAX = 0.1
L2_LAVA_SMOKE_FADE_POWER = 1.0
L2_LAVA_SMOKE_Y_OFFSET_FROM_LAVA_SURFACE = -15


PLAYER_TRAIL_COLOR_SNOW = (150, 165, 185)


ENABLE_METEOR_EFFECT = True
METEOR_MAX_COUNT = 12
METEOR_SPAWN_INTERVAL_MIN = 80
METEOR_SPAWN_INTERVAL_MAX = 800
METEOR_SPEED_MIN = 350
METEOR_SPEED_MAX = 800

METEOR_CORE_WIDTH_MIN = 2
METEOR_CORE_WIDTH_MAX = 4
METEOR_TOTAL_LENGTH_MIN = 25
METEOR_TOTAL_LENGTH_MAX = 65

METEOR_CORE_COLOR = (255, 255, 240)
METEOR_TRAIL_COLOR_START = (255, 200, 100)
METEOR_TRAIL_COLOR_END = (255, 100, 50)
METEOR_TRAIL_SEGMENTS = 4

METEOR_ANGLE_MIN_DEG = 60
METEOR_ANGLE_MAX_DEG = 120


DELAY_AFTER_JUMP_OUTCOME = 4000


ARIEL_IMAGE_FILENAME = "ariel.png"
ARIEL_DISPLAY_DURATION_ON_SCREEN = 2200
ARIEL_ANIM_SPEED = 400
ARIEL_TEXT_COLOR = (230, 230, 255)
ARIEL_TEXT_BOX_HEIGHT_PER_LINE = 25
ARIEL_MESSAGES = [
    "Gravity Node 1, Stabilized!",
    "Node 2 Online!",
    "Third node secured. Excellent work!",
    "System integrity at 40%!",
    "Halfway there!",
    "Node 6 active!",
    "Just a few more nodes to go. Don't stop now!",
    "Node 8 online. Almost there!",
    "System integrity at 90%!",
    "Final Node Active! GRAVITY SHIELD ONLINE!",
    "Bonus Node: Overcharging primary shield emitters!",
    "Bonus Node: Maximum stability achieved. Well done!"]


L2_HALFWAY_DURATION_MS = 30000 
L2_END_MESSAGE_TRIGGER_TIME_MS = 52000 



L2_CEILING_DECORATION_ENABLED = True
L2_CEILING_DECORATION_HORIZONTAL_FLIP_CHANCE = 0.5
L2_CEILING_DECO_MANUAL_TOP_Y_OFFSET = -80
L2_CEILING_DECO_RANDOM_TOP_Y_OFFSET_MIN = -400
L2_CEILING_DECO_RANDOM_TOP_Y_OFFSET_MAX = -180
L2_MINERAL_ASSETS_CONFIG = [
    ("mineral1.png", 60, 75),
    ("mineral2.png", 70, 70),
    ("mineral3.png", 75, 75),
]
L2_FOSSIL_ASSETS_CONFIG = [
    ("fossil1.png", 90, 90),
    ("fossil2.png", 190, 190),
    ("fossil3.png", 135, 135),
    ("fossil4.png", 75, 50),
    ("fossil5.png", 80, 60),
    ("fossil6.png", 70, 80),
    ("fossil7.png", 45, 45),
]
L2_MAX_CEILING_DECORATIONS_ON_SCREEN = 20
L2_CEILING_DECORATION_MIN_X_SPACING = 15
L2_CEILING_DECORATION_TARGET_AVG_SPACING = 150
L2_CEILING_DECORATION_SPAWN_X_VARIATION = 75
L2_CEILING_DECORATION_SPAWN_PROBABILITY = 0.85


L2_WIN_WHITE_FLASH_DURATION_MS = 1500 

L2_STAIRS_MANUAL_Y_OFFSET = 80